### ISSUE TITLE
More fine-grained IRQBALANCE_BANNED_CPULIST settings?

### ISSUE THREAD

**Issue by borkmann** [Irqbalance/irqbalance#199]
We have the following use case: I would only like to use the IRQBALANCE_BANNED_CPULIST feature for specific IRQs from (e.g.) specified netdevs (which are running XDP in our case). For all other IRQs, irqbalance should be able to use the full CPU set. Is there a way this configuration could be specified via irqbalance policy?

Thanks a lot,
Daniel

**Comment by nhorman** [comment]
hey daniel-
     Yes, you can absolutely do that using the --policyscript option.  policy script allows you to specify an executable (shell script, elf file, etc) to irqbalance, and for every irq that is detected, this executable is run, allowing you to specify whatever policy you like.  I would suggest you write a script that identifies your xdp enabled nics, and when found, sets the affinity for the interrupt to whatever white/blacklist you like, then echo ban=true to stdout, so that irqbalance knows not to further change the affinity.  See man irqbalance for additional details.

**Comment by nhorman** [comment]
Thats correct (well mostly correct).  The reasoning for not allowing balancing within a subset of CPUs is due to the conflict that potentially arises when the constrained set of cpus to balance over in your use case conflicts with other built in constraints (to be more specific, irqbalance, when balancing, selects a set of cpu based on numa node locality, then package locality, then cache locatiy).  if your constrained set overlaps those localities, you effectively get a logical and-ing of masks, that may result in an empty set of cpus.    You can avoid that by careful selection of your cpu set, but thats just about equivalent to using the numa_node and balance_level settings in the policy script (we can make it exactly equivalent if you want me to add package/cache/core selectors to the policyscript interface, which I'm happy to look at if you think its useful).

You can emulate some further balancing in policy script today if you like.  Normally ethernet irqs are assigned to a single cpu due to their higher trigger volume, and so you could write a policy script that, for the constrained set of cpus that you want to balance over, you round robin cpu affinity (i.e. if you have 6 irqs that you want to balance over 4 cpus, you could write the policy script to build an affinity mask for each irq where the mask was 1<<(cpunum mod 6) ), which is what would happen when irqbalance assigned affinity for the most part anyway.  The only difference would be that irqbalance would occasionally look at the load the irqs produced and consider merging irqs to a single cpu if it created a more balanced load.

let me know if you want to look at the additional balance settings I outlined above
