### ISSUE TITLE
irqbalance Aborts When Using irqbalance-ui

### ISSUE THREAD

**Issue by wcunning** [Irqbalance/irqbalance#261]
On Ubuntu 18.04 (I know, EOL), with irqbalance 1.3.0, when running irqbalance-ui, the irqbalance.service has the following error: 

wzn74z@USMPGUNDOSFCDSF:~$ sudo systemctl status irqbalance.service
● irqbalance.service - irqbalance daemon
   Loaded: loaded (/lib/systemd/system/irqbalance.service; enabled; vendor preset: enabled)
   Active: failed (Result: signal) since Tue 2023-03-07 14:21:18 EST; 5s ago
  Process: 21588 ExecStart=/usr/sbin/irqbalance --foreground $IRQBALANCE_ARGS (code=killed, signal=ABRT)
 Main PID: 21588 (code=killed, signal=ABRT)

Mar 07 14:21:08 USMPGUNDOSFCDSF systemd[1]: Started irqbalance daemon.
Mar 07 14:21:18 USMPGUNDOSFCDSF irqbalance[21588]: *** buffer overflow detected ***: /usr/sbin/irqbalance terminated
Mar 07 14:21:18 USMPGUNDOSFCDSF systemd[1]: irqbalance.service: Main process exited, code=killed, status=6/ABRT
Mar 07 14:21:18 USMPGUNDOSFCDSF systemd[1]: irqbalance.service: Failed with result 'signal'.

Is this known fixed in more up-to-date versions? If so, what version should compile on 18.04 with kernel 4.18.0-25-generic?

**Comment by nhorman** [comment]
From what you describe, that this sounds like a problem that was fixed in commit df7b5434bc19b3ea74af83393adbe901c2d11d8f, but I can't promise that.  If it is, it should be fixed by building irqbalance 1.7.0 or later. 

As for weather or not that will build on ubuntu, I have no idea.  It should, but no guarantees.  This is really the sort of question you should ask them, though given the EOL status of your distro, I'm guessing thats why you came here.
