### ISSUE TITLE
README

### ISSUE THREAD

**Issue by voidus** [Irqbalance/irqbalance#3]
Please add a readme with a short description of what irqbalance does and for whom it is useful.

**Comment by rickysarraf** [comment]
With laptops and handheld devices having multicore cpus, I think it warrants a section in the README on types of devices, and how it should be used. I say that because irqbalance has an option, "--oneshot", which is supposed to do its task once and then exit.

Is that mode/option designed for laptop ?
What should be the use case for laptops (and other similar devices) ?

**Comment by ppwaskie** [comment]
On Mon, Sep 28, 2015 at 7:26 AM, Ritesh Raj Sarraf
<notifications@github.com> wrote:
>
> With laptops and handheld devices having multicore cpus, I think it warrants a section in the README on types of devices, and how it should be used. I say that because irqbalance has an option, "--oneshot", which is supposed to do its task once and then exit.
>
> Is that mode/option designed for laptop ?

No.

> What should be the use case for laptops (and other similar devices) ?

Laptops actually would want interrupts to be moved more often than
servers.  The reason being for power efficiency.  If interrupts are
spread across CPUs once, then it is very difficult for the CPU to park
a core to drop into deeper C-states.  This is because that interrupt
can keep firing and waking up the CPU.  So just from the power
perspective, irq migration is necessary for laptops.  --oneshot would
not be ideal.

**Comment by sikarash** [comment]
Maybe "--powerthresh=<threshold>" option is useful for laptops?
