### ISSUE TITLE
Antergos Kernel Panics

### ISSUE THREAD

**Issue by Aeirex** [Irqbalance/irqbalance#64]
I am getting an unstable system after installing this into Antergos which is based off of Arch.

I am using the latest kernel.

**Comment by ppwaskie** [comment]
Hi Seth,

Can you post a snip of your kernel panic you're seeing?  Reporting an unstable system with no logs is not going to be useful.  Also please post the contents of "cat /proc/interrupts" so we can see what sort of devices are in the system attempting to be balanced.

And since Neil and I are kernel hackers, "latest kernel" means whatever patch Linus just pushed to his git repo a few minutes ago.  So providing the actual kernel version (uname -r) would be helpful as well.

Thanks,
-PJ

**Comment by nhorman** [comment]
agreed, a kernel panic is going to be required to figure out whats gone wrong here.

And please note, even though installing/running irqbalance seems to be the trigger for the panic, it  should be expected that any fix for this problem will be to kernel code.

**Comment by Aeirex** [comment]
Latest kernel causes the problem, my red light on the computer monitor turns red and doesn't flicker anymore.

Using Antergos. As for kernel logs, any clue how to get the error to output? I did some research, but I don't see a way to do it easily.

**Comment by ppwaskie** [comment]
irqbalance runs in userspace, and only tells the underlying interrupt handlers which CPUs to run on, if they choose to listen to it.  Stating using the "latest kernel" sounds suspect that a problem in the kernel is causing your issues.  If you get a panic, you can collect the panic from a serial console.  Without an actual kernel trace, I have no suggestion to what could be causing your issues.

Have you tried irqbalance on an "older" kernel?  Does the crash go away?  I suspect it will.

**Comment by Aeirex** [comment]
I switched off of Arch/Antergos, too many updates and hard to determine where the breakage is coming from. I gave up looking for logs, couldn't find one using journal.

**Comment by nhorman** [comment]
Is your last update saying that the problem no longer occurs?
