### ISSUE TITLE
Re-add affinity_hint support since kernel didn't remove it

### ISSUE THREAD

**Issue by ppwaskie** [Irqbalance/irqbalance#68]
Some specific devices need very exact control over where their interrupts get balanced to.  The affinity_hint mechanism, which is still present in /proc/irq/<irqnum>, is the current best way for a driver to export the desired IRQ affinity for a given device.  This affinity_hint support in irqbalance was removed, since a different approach was being planned in the kernel.  That approach was ultimately tabled, so we'd like this to be re-added to irqbalance.

**Comment by nhorman** [comment]
Can we get some more description on what exactly this device is, and how/why it needs exact control? I'd really like to understand some more about how/why this control is needed. I don't have an issue with doing it (though if we're re-adding it, we should look at some of the oddities that occur in conflicts between affinity_hint and user policy, like banning cpus), and I'd like to know more about the hardware using this feature.

FWIW, until we get this done, irqbalance actually can still make use of affinity_hint.  The policyscript option lets us specify a script that can tell irqbalance to ignore balancing a given interrupt, and at the same time echo the affinity_hint value for an irq into its smp_affinity value.  Perhaps, rather than add the former affinity_hint support back exactly as it was, it would be worth considering enhancing/changing the policyscript support such that we can more easily package vendor scripts to support individual hardware needs like this

**Comment by nhorman** [comment]
How about something like this:
https://github.com/Irqbalance/irqbalance/tree/affinity

It expands the --policyscript option to allow its argument to be either a single script, or a directory containing an arbitrary number of scripts that can be executed sequentially, with exit codes being used to indicate if a given script wants to claim irqs belonging to various devices.

I was thinking then that we could incorporate a colleciton of policy scripts that can be distributed for packaging, and specifically include  a script that detects the hardware in question here, copies the affinity_hint value for the irq to its smp_affinity file, and informs irqbalance that it should no longer modify this irq affinity by echoing ban=true back.

Thoughts?

**Comment by ppwaskie** [comment]
I actually really like the policyscript approach.  And the patch to me looks good.

The device in question isn't something I can publicly discuss unfortunately.  The only thing I can discuss is that it requires, by spec of the device, that the receive traffic be processed on the same CPU as another function of that hardware.  And the only way we can guarantee that is to tie the specific interrupts to the same CPU.  But they also need to allow the balancer to handle the other interrupts on the system.  It's very specific, but it does need this extra policy to function properly.  Hope this helps a bit more.

**Comment by nhorman** [comment]
yeah, I can understand something being under NDA at the moment, but that makes the policyscript approach that much more appealing I think.  With that approach, you can when ready, submit a script to be bundled with the irqbalance daemon to detect and assert policy as needed for this device without affecting other devices.  I'll finish testing the above pull request and merge it shortly.  Should be in Fedora prior to your ability to disclose info on the device

**Comment by ppwaskie** [comment]
Thanks Neil, this is a better approach in my opinion.  Appreciate you jumping on this so quick.
